name: funchook

on:
  workflow_dispatch:
    inputs:
      funchook:
        required: true
        description: "funchook ref"
      release:
        required: false
        default: "false"
        description: "create release or not"

jobs:
  funchook:
    name: Build FuncHook
    runs-on: windows-latest
    steps:
      - name: Checkout FuncHook
        uses: actions/checkout@v2
        with:
          repository: kubo/funchook
          ref: ${{github.event.inputs.funchook}}
          submodules: true
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
      - name: Run cmake
        run: |
          cmake -B build
          cmake --build build --config MinSizeRel
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: funchook
          path: build/MinSizeRel/funchook.dll
      - name: Create Release
        if: ${{github.event.inputs.release == 'true'}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: funchook-${{github.event.inputs.funchook}}
          release_name: Release FuncHook ${{github.event.inputs.funchook}}
          draft: true
          prerelease: false
      - name: Upload Asset
        if: ${{github.event.inputs.release == 'true'}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/MinSizeRel/funchook.dll
          asset_name: funchook.dll
          asset_content_type: application/octet-stream